### ISSUE TITLE
文字化け解消のアイディア

### ISSUE THREAD

**Issue by tyamahori** [Meiryo7743/getData_covid19-ichikawa#1]
はじめまして。
本八幡bot さんのツイートを拝見し、お役にたてればと思い、ここに雑ではありますが、自分なりの解決策を記したいと思います。

# curlコマンド
`curl -s --connect-timeout 60 --max-time 120 https://www.city.ichikawa.lg.jp/pub01/hasseijokyo.html | iconv -f Shift_JIS -t UTF8`

こちらをターミナルで叩けば、期待したhtmlファイルが出力されるかと思います。

# PHP
自分の場合Pythonは不慣れなためPHPで対応します。
以下のサンプルを 適当なファイル名 index.php などにコピペしてもらい、動かしてみてください。

```
<?php

$curl = curl_init('https://www.city.ichikawa.lg.jp/pub01/hasseijokyo.html');

curl_setopt($curl, CURLOPT_CUSTOMREQUEST, "GET");
curl_setopt($curl, CURLOPT_RETURNTRANSFER, TRUE);
curl_setopt($curl, CURLOPT_SSL_VERIFYPEER, FALSE);
curl_setopt($curl, CURLOPT_SSL_VERIFYHOST, FALSE);
curl_setopt($curl, CURLOPT_FOLLOWLOCATION, TRUE);

$output = curl_exec($curl);
curl_close($curl);

$output = iconv("Shift-JIS", "UTF-8", $output);
$output = str_replace('Shift_JIS', 'UTF-8', $output);

file_put_contents('index.html', $output);
```

# スプレッドシート
自分は、スプレッドシートに不慣れなため、検索した結果役立ちそうなリンクをここに共有いたします。

https://qiita.com/pkino/items/56885efb9dd97f48738f

**Comment by Meiryo7743** [comment]
cURL と PHP の 2 通りによる解決案のご提示，ありがとうございます。

UTF-8 に変換されたページを定期的に自動生成するために，GitHub Actions を使おうと考えているところです。

cURL による方法であれば，GitHub Actions でも実行できそうなので，参考にさせていただきます。

---

> 自分は、スプレッドシートに不慣れなため、検索した結果役立ちそうなリンクをここに共有いたします。
> 
> https://qiita.com/pkino/items/56885efb9dd97f48738f

![docs google com_spreadsheets_d_1wx_fUuTn2fVAofmSRTV5H5UVZ1I6hbuHRUYIAq_V1o4_edit(PC)](https://user-images.githubusercontent.com/46659204/83344699-67eede00-a345-11ea-8e22-ca3828047807.png)

上記リンク先の方法を試してみたのですが，なぜか `0` という値が返って来ますね……。

色々と調べてみましたが，その原因はわかりませんでした。もしかしたら，GAS のランタイムが Rhino から V8 に移行したことが影響しているかもしれません。

とはいえど，有意義な情報のご提供，ありがとうございました。

**Comment by Meiryo7743** [comment]
文字化け問題が解決したため，クローズいたします。
